-- Example seed SQL (rename to *.sql to apply on API startup).
-- Statements are applied once per file checksum via schema_seeds.

-- INSERT INTO books (
--   isbn, title, authors, publication_year, genre, publisher,
--   location, notes, source
-- ) VALUES (
--   '9780451524935',
--   'Nineteen Eighty-Four',
--   'George Orwell',
--   1993,
--   'Clásico',
--   'Signet Classics',
--   'B2',
--   'Ejemplo SQL',
--   'seed'
-- )
-- ON CONFLICT (isbn) DO NOTHING;
